# Generated by Django 4.2.3 on 2023-09-15 02:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_of_creation',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
